Resources:
  BuildCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: !Ref CodeBuildImage
        Type: LINUX_CONTAINER
      ServiceRole: !ImportValue ci-core-infra-common-codebuild-role-arn
      EncryptionKey: "alias/codepipeline-kms-key"
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            build:
              commands:
                - echo 'Building...'

  TestCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: !Ref CodeBuildImage
        Type: LINUX_CONTAINER
      ServiceRole: !ImportValue ci-core-infra-common-codebuild-role-arn
      EncryptionKey: "alias/codepipeline-kms-key"
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            build:
              commands:
                - echo 'Testing...'                

  DeployingCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: !Ref CodeBuildImage
        Type: LINUX_CONTAINER
      ServiceRole: !ImportValue ci-core-infra-common-codebuild-role-arn
      EncryptionKey: "alias/codepipeline-kms-key"
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            build:
              commands:
                - echo 'Deploying...'

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !ImportValue ci-core-infra-artifacts-bucket-name
        EncryptionKey:
          Id: !ImportValue ci-core-infra-artifacts-kms-key-arn
          Type: "KMS"
      Name: !Ref CodePipelineName
      RestartExecutionOnUpdate: true
      RoleArn: !ImportValue ci-core-infra-codepipeline-execution-role-arn
      Stages:
        - Name: Source
          Actions:
            - ActionTypeId:
                Category: Source
                Owner: AWS
                Version: "1"
                Provider: CodeStarSourceConnection
              OutputArtifacts:
                - Name: GitHubSource
              RunOrder: 1
              Name: Clone-From-GitHub
              Configuration:
                ConnectionArn: !Ref CodeStarConnectionArn
                FullRepositoryId: !Ref GitHubRepo
                BranchName: !Ref GitHubBranch
        - Name: Build
          Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              InputArtifacts:
                - Name: GitHubSource
              OutputArtifacts:
                - Name: BuiltSource
              Name: Build
              Configuration:
                ProjectName: !Ref BuildCodeBuildProject
        - Name: Test
          Actions:
            - ActionTypeId:
                Category: Test
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              InputArtifacts:
                - Name: BuiltSource
              Name: Test
              Configuration:
                ProjectName: !Ref TestCodeBuildProject
        - Name: Deploy
          Actions:
            - ActionTypeId:
                Category: Build # note there is no deploy only build or test.
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              InputArtifacts:
                - Name: BuiltSource
              Name: Deploy
              Configuration:
                ProjectName: !Ref DeployingCodeBuildProject
