version: 0.2
env: 

phases:
  pre_install:
    commands:
      - echo "Fetching certificate from Certee"
      - certee-fetch

  install:
    commands:
      - node -v
      - npm ci

  build:
    commands:
      - echo "Building repo"
      - npm run build

artifacts:
  files:
    - ./**/*