Description: |
  Template for Web Components CICD pipeline

Parameters:
  PipelineName:
    Type: String
    Description: Identifier for pipeline
  ArtifactEncryptionKey:
    Type: String
    Description: Encryption Key used for storing build artifacts
  CodeStarConnectionArn:
    Type: String
    Description: Connection Arn to allow cloning from Github
  GithubRepo:
    Type: String
    Description: Github Repo including Owner
  MainBranch:
    Type: String
    Default: main
    Description: Main Branch that is used for all deployments
  CodeBuildImage:
    Type: String
    Default: aws/codebuild/standard:5.0
    Description: Image used for CodeBuild

Resources:
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Ref PipelineName
      RestartExecutionOnUpdate: true
      RoleArn: !ImportValue ci-core-infra-codepipeline-execution-role-arn
      # ArtifactStore is an S3 bucket where codepipeline stores files
      ArtifactStore:
        Location: ipwb-pipeline-artifacts
        Type: S3
        EncryptionKey:
          Id: !Ref ArtifactEncryptionKey
          Type: 'KMS'
      # Stages are the same as stages in Jenkins
      Stages:
        - Name: Source
          # Actions are the same as Jenkins steps
          Actions:
            - Name: CloneFromGithub
              RunOrder: 1
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: "1"
                Provider: CodeStarSourceConnection
              Configuration:
                ConnectionArn: !Ref CodeStarConnectionArn
                FullRepositoryId: !Ref GithubRepo
                BranchName: !Ref MainBranch
              OutputArtifacts:
                - Name: GithubSource
        - Name: Install
          Actions:
            - Name: Install Dependencies
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: GithubSource
              OutputArtifacts:
                - Name: InstalledSource
              Configuration:
                ProjectName: !Ref InstallCodeBuildProject

  InstallCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: !Ref CodeBuildImage
        Type: LINUX_CONTAINER
      ServiceRole: !ImportValue ci-core-infra-common-codebuild-role-arn
      EncryptionKey: "alias/codepipeline-kms-key"
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml




      
